services:
  - type: web
    name: tronco-arepa-backend
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false