services:
  - type: web
    name: tronco-arepa-backend
    runtime: docker
    plan: free
    rootDir: .
    dockerfilePath: ./tronco-arepa-backend/Dockerfile
    dockerContext: ./tronco-arepa-backend
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: true
      - key: SPRING_DATASOURCE_USERNAME
        sync: true
      - key: SPRING_DATASOURCE_PASSWORD
        sync: true