services:
  - type: web
    name: tronco-arepa-backend
    runtime: docker
    plan: free
    rootDir: tronco-arepa-backend
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: SPRING_DATASOURCE_URL
        sync: true
      - key: SPRING_DATASOURCE_USERNAME
        sync: true
      - key: SPRING_DATASOURCE_PASSWORD
        sync: true